export { serverTypeLabels, stateLabels } from "./dashboardLabels";
import { useBackupDashboardActions } from "./dashboard/backupsStore";
import { useFileDashboardActions } from "./dashboard/filesStore";
import { useModDashboardActions } from "./dashboard/modsStore";
import { useMonitoringDashboardActions } from "./dashboard/monitoringStore";
import { useServerDashboardActions } from "./dashboard/serversStore";
import { useSettingsDashboardActions } from "./dashboard/settingsStore";
import {
  agentStatus,
  backups,
  curseForgeApiKey,
  deployingServersCount,
  files,
  isAgentUnavailable,
  isApplyingUpdate,
  isConfigLoading,
  isConfigSaving,
  isCrashReportLoading,
  isCreatingServer,
  isDashboardInitialLoading,
  isDashboardLoaded,
  isFileLoading,
  isFileSaving,
  isLoading,
  isLogLoading,
  isModLoading,
  isMonitoringHistoryLoading,
  isMonitoringLoading,
  isSavingSettings,
  isUpdateLoading,
  logs,
  mods,
  monitoring,
  monitoringHistory,
  monitoringHistoryMeta,
  monitoringWindow,
  monitoringStatus,
  offlineServersCount,
  onlineServersCount,
  selectedServer,
  selectedServerConfig,
  selectedServerCrashReports,
  selectedServerFileContent,
  selectedServerFilePath,
  selectedServerFileSearchResults,
  selectedServerFiles,
  selectedServerId,
  selectedServerLogs,
  selectedServerMods,
  servers,
  settings,
  stableServersCount,
  updateStatus,
} from "./dashboard/state";

const serverActions = useServerDashboardActions();
const monitoringActions = useMonitoringDashboardActions();
const fileActions = useFileDashboardActions();
const modActions = useModDashboardActions();
const backupActions = useBackupDashboardActions();
const settingsActions = useSettingsDashboardActions({
  loadAgentStatus: monitoringActions.loadAgentStatus,
  loadDashboard: () => serverActions.loadDashboard(),
});

export function useDashboardStore() {
  return {
    servers,
    logs,
    backups,
    mods,
    files,
    isLoading,
    isDashboardLoaded,
    isDashboardInitialLoading,
    isMonitoringLoading,
    isSavingSettings,
    isUpdateLoading,
    isApplyingUpdate,
    isCreatingServer,
    selectedServerId,
    selectedServer,
    selectedServerLogs,
    selectedServerCrashReports,
    selectedServerConfig,
    selectedServerFiles,
    selectedServerFilePath,
    selectedServerFileContent,
    selectedServerFileSearchResults,
    selectedServerMods,
    isLogLoading,
    isCrashReportLoading,
    isConfigLoading,
    isConfigSaving,
    isFileLoading,
    isFileSaving,
    isModLoading,
    isMonitoringHistoryLoading,
    curseForgeApiKey,
    agentStatus,
    settings,
    updateStatus,
    monitoring,
    monitoringHistory,
    monitoringHistoryMeta,
    monitoringWindow,
    onlineServersCount,
    offlineServersCount,
    deployingServersCount,
    stableServersCount,
    isAgentUnavailable,
    monitoringStatus,
    ...serverActions,
    ...monitoringActions,
    ...fileActions,
    ...modActions,
    ...backupActions,
    ...settingsActions,
  };
}
